import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://127.0.0.1:5000/');
  await page.getByRole('link', { name: 'Course Management' }).click();
  await page.getByRole('button', { name: 'Add Course' }).click();
  await page.getByLabel('Institution *').selectOption('dut');
  await page.getByRole('textbox', { name: 'Course Name *' }).click();
  await page.getByRole('textbox', { name: 'Course Name *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Course Name *' }).fill('Bachelor of ');
  await page.getByRole('textbox', { name: 'Course Name *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Course Name *' }).fill('Bachelor of E');
  await page.getByRole('textbox', { name: 'Course Name *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Course Name *' }).fill('Bachelor of Engineering in ');
  await page.getByRole('textbox', { name: 'Course Name *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Course Name *' }).fill('Bachelor of Engineering in C');
  await page.getByRole('textbox', { name: 'Course Name *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Course Name *' }).fill('Bachelor of Engineering in Civil');
  await page.getByRole('textbox', { name: 'Description *' }).click();
  await page.getByRole('textbox', { name: 'Description *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Description *' }).fill('C');
  await page.getByRole('textbox', { name: 'Description *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Description *' }).fill('Comprehensive program focused on infrastructure design, construction management, and sustainable engineering practices.');
  await page.getByRole('textbox', { name: 'Duration *' }).click();
  await page.getByRole('textbox', { name: 'Duration *' }).fill('4 years');
  await page.getByLabel('Study Mode *').selectOption('full-time');
  await page.getByRole('button', { name: 'Save Course' }).click();
  await page.getByLabel('Filter').selectOption('dut');
  await page.getByRole('textbox', { name: 'Search courses...' }).click();
  await page.getByRole('textbox', { name: 'Search courses...' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Search courses...' }).fill('B');
  await page.getByRole('textbox', { name: 'Search courses...' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Search courses...' }).fill('Bachelor of ');
  await page.getByRole('textbox', { name: 'Search courses...' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Search courses...' }).fill('Bachelor of E');
  await page.getByRole('textbox', { name: 'Search courses...' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Search courses...' }).fill('Bachelor of Engineering in ');
  await page.getByRole('textbox', { name: 'Search courses...' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Search courses...' }).fill('Bachelor of Engineering in C');
  await page.getByRole('textbox', { name: 'Search courses...' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Search courses...' }).fill('Bachelor of Engineering in Civil ');
  await page.getByRole('textbox', { name: 'Search courses...' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Search courses...' }).fill('Bachelor of Engineering in Civil E');
  await page.getByRole('textbox', { name: 'Search courses...' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Search courses...' }).fill('Bachelor of Engineering in Civil Engineering');
});