import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://127.0.0.1:5000/');
  await page.getByRole('navigation').getByRole('link', { name: 'START MY SEARCH!' }).click();
  await page.getByRole('link', { name: 'Edit' }).click();
  await page.locator('#subject').selectOption('mathematics');
  await page.locator('#grade').selectOption('11');
  await page.getByPlaceholder('85').click();
  await page.getByPlaceholder('85').fill('78');
  await page.getByRole('button', { name: '+ Add Another Subject' }).click();
  await page.getByRole('combobox').nth(2).selectOption('afrikaans-home-language');
  await page.getByPlaceholder('85').nth(1).click();
  await page.getByPlaceholder('85').nth(1).fill('67');
  await page.getByRole('combobox').nth(3).selectOption('12');
  await page.locator('#grade').selectOption('12');
  await page.getByRole('button', { name: '+ Add Another Subject' }).click();
  await page.getByRole('combobox').nth(4).selectOption('information-technology');
  await page.getByPlaceholder('85').nth(2).click();
  await page.getByPlaceholder('85').nth(2).fill('89');
  await page.getByRole('combobox').nth(5).selectOption('12');
  await page.getByRole('button', { name: '+ Add Another Subject' }).click();
  await page.locator('div:nth-child(4) > .subject-row > .form-group.flex-2 > .subject-select').selectOption('computer-applications-technology');
  await page.getByPlaceholder('85').nth(3).click();
  await page.getByPlaceholder('85').nth(3).fill('80');
  await page.locator('div:nth-child(4) > .subject-row > div:nth-child(3) > .subject-grade').selectOption('12');
  await page.locator('#province').selectOption('kwazulu-natal');
  await page.getByRole('textbox', { name: 'e.g., Sandton' }).click();
  await page.getByRole('textbox', { name: 'e.g., Sandton' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'e.g., Sandton' }).fill('D');
  await page.getByRole('textbox', { name: 'e.g., Sandton' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'e.g., Sandton' }).fill('Durban');
  await page.getByText('No, I prefer to stay local').click();
  await page.getByText('Contact (In Person)').click();
  await page.getByText('Bachelor\'s Degree').click();
  await page.getByRole('checkbox', { name: 'Diploma', exact: true }).check();
  await page.getByText('Certificate').click();
  await page.getByPlaceholder('e.g., 50000').click();
  await page.getByPlaceholder('e.g., 50000').fill('60000');
  await page.locator('label').filter({ hasText: '✓ Yes, I need support' }).click();
  await page.getByRole('textbox', { name: 'Please describe the type of' }).click();
  await page.getByRole('textbox', { name: 'Please describe the type of' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Please describe the type of' }).fill('I');
  await page.getByRole('textbox', { name: 'Please describe the type of' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Please describe the type of' }).fill('I need financial aid to study ');
  await page.locator('.career-select').first().selectOption('data-scientist');
  await page.locator('div:nth-child(2) > .career-select').selectOption('software-developer');
  await page.locator('div:nth-child(3) > .career-select').selectOption('business-analyst');
  await page.locator('label').filter({ hasText: '✓ Yes, I\'ll apply for NSFAS' }).click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Find My Perfect Match' }).click();
});