"""Initial clean schema

Revision ID: 5ee8f4adae88
Revises: 
Create Date: 2025-11-04 01:14:01.753354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ee8f4adae88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('ws_university', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=200), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.create_unique_constraint('uq_ws_university_name', ['name'])
        batch_op.drop_column('university_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ws_university', schema=None) as batch_op:
        batch_op.add_column(sa.Column('university_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('website')
        batch_op.drop_column('location')
        batch_op.drop_column('id')
'''
    with op.batch_alter_table('ws_program', schema=None) as batch_op:
        batch_op.add_column(sa.Column('program_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'university', ['university_id'], ['university_id'])
        batch_op.alter_column('program_name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('fees')
        batch_op.drop_column('study_mode')
        batch_op.drop_column('location')
        batch_op.drop_column('id')

    # ### end Alembic commands ###

    '''