"""Add bursary model

Revision ID: c4ad2a52e8d5
Revises: 
Create Date: 2025-11-01 18:47:31.973315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4ad2a52e8d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.drop_column('min_aggregate')
        batch_op.drop_column('essential_requirements')
        batch_op.drop_column('accreditation')
        batch_op.drop_column('tuition_fee')

    with op.batch_alter_table('requirement', schema=None) as batch_op:
        batch_op.drop_column('subject_type')
        batch_op.drop_column('notes')
        batch_op.drop_column('comparator')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comparator', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('subject_type', sa.VARCHAR(length=20), nullable=True))

    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tuition_fee', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('accreditation', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('essential_requirements', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('min_aggregate', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
